[package]
name = "nz-rust-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4.10"
nz_rust = { path = ".." }

[[bin]]
name = "protocol"
path = "fuzz_targets/protocol.rs"
test = false
doc = false
bench = false

[[bin]]
name = "sql_lexer"
path = "fuzz_targets/sql_lexer.rs"
test = false
doc = false
bench = false

[[bin]]
name = "wire_frames"
path = "fuzz_targets/wire_frames.rs"
test = false
doc = false
bench = false

[workspace]
members = ["."]
